Change to config based approach
Major bug though currently since config appears to clobber functions:

  atom.config.get('script.grammars.Perl')["File Based"]()
  TypeError: Property 'File Based' of object #<Object> is not a function
  atom.config.get('script.grammars.Perl')["File Based"]
  Object {}